### ISSUE TITLE
Fail to push container image to Snowflake

### ISSUE THREAD

**Issue by santteegt** [Snowflake-Labs/llm-bootcamp-build-2023#10]
Hey,

I'm trying to push the container image for day 2 but I'm getting the following error after calling `docker push ....`

```
The push refers to repository [sfsenorthamerica-build_spcs11.registry.snowflakecomputing.com/db_user0029/schema_llm/image_repo/llm-bootcamp]
Get "https:/v2/": http: no Host in request URL
```

According to this [post](https://stackoverflow.com/questions/49810278/why-can-not-push-image-to-my-private-registry) docker has issues when the domain includes an underscore character. What can I do to solve this?

**Comment by iamontheinet** [comment]
Hi @santteegt! Please replace underscore with hyphen in your account name like so `sfsenorthamerica-build-spcs11` and try again.
