### ISSUE TITLE
Logging in using the CLI

### ISSUE THREAD

**Issue by midstreamer** [Snowflake-Labs/llm-bootcamp-build-2023#11]
I'm following the instructions for day two prep and running into issues with the URL. I was able to create the docker image, but I'm not able to log in to SFCS to push the docker image. I am using the following command: 

`docker login sfsenorthamerica-your-account-name.registry.snowflakecomputing.com `

I am replacing your-account-name with the account locator information from my account, but I am getting a 404 error. Should I be using another parameter for your-account-name? I tried using my username, but that didn't work either.

**Comment by skhara-snowflake** [comment]
Hey @midstreamer - if your account name is "sfsenorthamerica-build_spcs3", just replace this in the account name portion but remember to replace the underscore with hyphen. Your docker login command should look something like- 
`docker login sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com`

Hope this helps!
