### ISSUE TITLE
Error while deploying model

### ISSUE THREAD

**Issue by roshanbagde** [Snowflake-Labs/llm-bootcamp-build-2023#12]
Hi Team

I am getting below error while deploying the model  (running below code).

/*
%%time
# Optionally enable INFO log level
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)

llama_model_ref.deploy(
    deployment_name="llama_predict", 
    platform=deploy_platforms.TargetPlatform.SNOWPARK_CONTAINER_SERVICES,
    permanent=True, 
    options={"compute_pool": COMPUTE_POOL, "num_gpus": 1})

llama_model_ref = model_registry.ModelReference(registry=registry,model_name=MODEL_NAME,model_version=MODEL_VERSION)
llama_model_ref
*/

Getting below error , while running above code. Tried multiple times, even after 2-3 hours getting same error. Nothing much to debug here.-> 
RuntimeError: (1301) ResourceType.JOB 01b0ccb7-0001-ed51-0046-4c870001ca16 failed.
Status: ResourceStatus.FAILED 

Could you please check on this.

**Comment by skhara-snowflake** [comment]
Duplicate error. @roshanbagde request you to follow/add context to the issue below-
https://github.com/Snowflake-Labs/llm-bootcamp-build-2023/issues/6
