### ISSUE TITLE
"docker buildx build" requires exactly 1 argument issue

### ISSUE THREAD

**Issue by anmca** [Snowflake-Labs/llm-bootcamp-build-2023#13]
Day1 all successfully done! 💯  Thanks for clear instructions. 
However Docker is throwing an error when building the container.

ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

**Comment by skhara-snowflake** [comment]
Hi @anmca,
Can you try the fix as discussed in another similar issue-
https://github.com/Snowflake-Labs/llm-bootcamp-build-2023/issues/7#issuecomment-1842085447

**Comment by shulik7** [comment]
@anmca  You may have missed the "." at the very end of the command, which refers to current directory.

**Comment by anmca** [comment]
found the issue...missing the dot current directory at the end. Thanks for Looking! you are awesome!! guys!

**Comment by anmca** [comment]
my comment didn't get posted earlier..just checked ..thanks shuilk7.. just seeing your comment now.
