### ISSUE TITLE
Error in Final Lab Step: Unable to Push Docker Image - 'no Host in request URL

### ISSUE THREAD

**Issue by jaredbach** [Snowflake-Labs/llm-bootcamp-build-2023#14]
I am receiving an error on this the final step of the lab, where you are supposed to push the docker image:

`docker push sfsenorthamerica-build_spcs6.registry.snowflakecomputing.com/db_user0029/schema_llm/image_repo/llm-bootcamp:latest`

Terminal Output:

```
The push refers to repository [sfsenorthamerica-build_spcs6.registry.snowflakecomputing.com/db_user0029/schema_llm/image_repo/llm-bootcamp]
Get "https:/v2/": http: no Host in request URL
```

I am not sure what could be causing this issue. Thanks!

**Comment by jaredbach** [comment]
I solved this issue, I needed to replaced the _ with a hyphen - in the URL. My bad! Hope this helps others. Be ware!

**Comment by HoaXHoang** [comment]
> I solved this issue, I needed to replaced the _ with a hyphen - in the URL. My bad! Hope this helps others. Be ware!

Hey @jaredbach, what exactly was your new command? I've tried replacing different variations of the underscore with hyphen and it keeps stating `An image does not exist locally with the tag:`

**Comment by anmca** [comment]
did you change it and rebuilt the image before tag too or let it be with build_spcsx. I see build_spcsx when I'm on snowflake site. why need to change it to '-' Thanks

**Comment by anmca** [comment]
never mind. After loosing track of multiple changes finally got it to work. After image creation. I removed the tag with '_' version and rerun tag with '-' and login  and somehow need to recreate tag after login..but it did work.
