### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by VicenteAR** [Snowflake-Labs/llm-bootcamp-build-2023#22]
I have an issue when deploying the model. After registering it, I proceed to deploy it in snowflake. Nevertheless, I found a problem with the tokens: 

`WARNING:snowflake.ml.model._deploy_client.utils.snowservice_client:Best-effort log streaming from SPCS will be enabled when python logging level is set to INFO.Alternatively, you can also query the logs by running the query 'CALL SYSTEM$GET_JOB_LOGS('01b0ce88-0001-edf3-0046-31870007e19a', 'kaniko')'
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 2: 
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 6: 
INFO:snowflake.ml._internal.utils.log_stream_processor:Stopping file monitoring job...
INFO:snowflake.ml._internal.utils.log_stream_processor:sh: can't kill pid -1: No such process
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 12: }
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 13: 
': No such file or directoryutils.log_stream_processor:cat: can't open '/snowflake/session/token
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 15: 
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 16: 
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 17: }
: not foundake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 18: 
': No such file or directoryutils.log_stream_processor:md5sum: can't open '/snowflake/session/token
INFO:snowflake.ml._internal.utils.log_stream_processor:Monitoring session token changes in the background...
INFO:snowflake.ml._internal.utils.log_stream_processor:/DB_USER0032.SCHEMA_LLM._SYSTEM_REGISTRY_DEPLOYMENTS_STAGE/llama_predict/models/3d6f3938943211ee9f1c448a5b2195b7/kaniko_shell_script_fixture.sh: line 37: syntax error: unexpected ")" (expecting "then")
INFO:snowflake.ml._internal.utils.log_stream_processor:`

and the following python error (see attached file). 

What should I do? Thanks for your support.
[error.log](https://github.com/Snowflake-Labs/llm-bootcamp-build-2023/files/13583263/error.log)

**Comment by iamontheinet** [comment]
Closing as dup of #6
