### ISSUE TITLE
Docker Push Seems To Be not working

### ISSUE THREAD

**Issue by Paresh10** [Snowflake-Labs/llm-bootcamp-build-2023#28]
Hi there,

I was able to complete all the steps until `docker tag` command. But when I try to push to docker hub. I am seeing the below message. Not sure if it is an error or expected.

```
docker push sfsenorthamerica-build_spcs6.registry.snowflakecomputing.com/db_user0006/schema_llm/image_repo/llm-bootcamp:latest

The push refers to repository [sfsenorthamerica-build_spcs6.registry.snowflakecomputing.com/db_user0006/schema_llm/image_repo/llm-bootcamp]

Get "https:/v2/": http: no Host in request URL
```

**Comment by iamontheinet** [comment]
Hey @Paresh10! Replace "_" (underscore) with "-" (hyphen) in your account name. Like so `sfsenorthamerica-build-spcs6` and it should work.

**Comment by sbrudz** [comment]
It's due to this bug in docker: https://github.com/moby/moby/issues/34975

**Comment by Paresh10** [comment]
@iamontheinet Thank you. That did the trick. I am currently waiting for the push to be completed but it looks like it should be done without any issues. @sbrudz thank you for the reference.
