### ISSUE TITLE
docker won't deploy

### ISSUE THREAD

**Issue by azfeenixfire** [Snowflake-Labs/llm-bootcamp-build-2023#29]
I have followed the steps for the docker deploy, confirmed I can successfully log into the snowflake instance, but keep getting an error on docker deploy stating "no host in request URL".  Copy of my command and response below.  I have double checked the url several times but I'm not seeing what the issue is.

docker push sfsenorthamerica-build_spcs3.registry.snowflakecomputing.com/db_user0012/schema_llm/image_repo/llm-bootcamp:latest
The push refers to repository [sfsenorthamerica-build_spcs3.registry.snowflakecomputing.com/db_user0012/schema_llm/image_repo/llm-bootcamp]
Get "https:/v2/": http: no Host in request URL

**Comment by iamontheinet** [comment]
Replace "_" (underscore) with "-" (hyphen) in your account name. Like so sfsenorthamerica-build-spcs6 and it should work.
