### ISSUE TITLE
No HTTPS proxy/host

### ISSUE THREAD

**Issue by virtuosi** [Snowflake-Labs/llm-bootcamp-build-2023#32]
llm-bootcamp-build-2023\day2>docker login sfsenorthamerica-sfsenorthamerica-build-spcs11.registry.snowflakecomputing.com
Username: USER0023
Password: 
Error response from daemon: Get "https://sfsenorthamerica-sfsenorthamerica-build-spcs11.registry.snowflakecomputing.com/v2/": dialing sfsenorthamerica-sfsenorthamerica-build-spcs11.registry.snowflakecomputing.com:443 container via direct connection because  has no HTTPS proxy: resolving host sfsenorthamerica-sfsenorthamerica-build-spcs11.registry.snowflakecomputing.com: lookup sfsenorthamerica-sfsenorthamerica-build-spcs11.registry.snowflakecomputing.com: no such host

Thank you for your help in advance!

**Comment by virtuosi** [comment]
Thank you! Issue resolved.

**Comment by vinay235** [comment]
> Thank you! Issue resolved.

Are you able to login to snowflake using that version? My version is showing me a blank page after I login.

**Comment by virtuosi** [comment]
Yes, Vinay; I can login and see this:
![image](https://github.com/Snowflake-Labs/llm-bootcamp-build-2023/assets/84921407/6ca7b6ee-f26d-41f8-84ea-59d31abf5a77)

**Comment by vinay235** [comment]
> Yes, Vinay; I can login and see this: ![image](https://private-user-images.githubusercontent.com/84921407/288495846-6ca7b6ee-f26d-41f8-84ea-59d31abf5a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODQ1NDgsIm5iZiI6MTcwMTg4NDI0OCwicGF0aCI6Ii84NDkyMTQwNy8yODg0OTU4NDYtNmNhN2I2ZWUtZjI2ZC00MWY4LTg0ZWEtNTlkMzFhYmY1YTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE3MzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjIxOGIyY2NhYjdjZTk3YmJhYmFjOTkwOGYxZDM4NTZkZjdkOTJkNzAxM2IyZGQ4MDhjZTBhMzUzMGQ0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MUumX191ESdlNpZJWv9Gb6fjtTf7gy-gJA5z5fm5ZHI)

I actually meant Snowfight and not the streamlit app, can you login and access the snowsight link?

**Comment by virtuosi** [comment]
Snowflake link like https://sfsenorthamerica-build_spcs11.snowflakecomputing.com/ or https://sfsenorthamerica-build-spcs11.snowflakecomputing.com/ ? If so, I logged in and see this for either links:
![image](https://github.com/Snowflake-Labs/llm-bootcamp-build-2023/assets/84921407/42ba9c20-c244-4b17-bd35-7dd857ca6a6c)
