### ISSUE TITLE
Day 2 Prep - Error in pushing image to docker

### ISSUE THREAD

**Issue by karenderer** [Snowflake-Labs/llm-bootcamp-build-2023#7]
I'm getting an error in this step to push the image to Snowflake Registry: 

```
Replace your-account-name with your account name and your-db-name with the name of your database in lowercase and then run the following command

docker push sfsenorthamerica-your-account-name.registry.snowflakecomputing.com/your-db-name/schema_llm/image_repo/llm-bootcamp:latest
```

Terminal output
```
(base) llm-bootcamp-build-2023/day2 [main●] » docker tag llm-bootcamp:latest sfsenorthamerica-build_spcs5.registry.snowflakecomputing.com/db_user0012/schema_llm/image_repo/llm-bootcamp:latest
(base) llm-bootcamp-build-2023/day2 [main●] » docker login sfsenorthamerica-build_spcs5.registry.snowflakecomputing.com
Username: USER0012
Password: 
Login Succeeded
(base) llm-bootcamp-build-2023/day2 [main●] » docker push sfsenorthamerica-build_spcs5.registry.snowflakecomputing.com/db_user0012/schema_llm/image_repo/llm-bootcamp:latest
The push refers to repository [sfsenorthamerica-build_spcs5.registry.snowflakecomputing.com/db_user0012/schema_llm/image_repo/llm-bootcamp]
Get "https:/v2/": http: no Host in request URL
```

**Comment by Luismbpr** [comment]
I am having the same issue.

Terminal output
```(llm-bootcamp) luis@Luiss-MacBook-Pro day2 % docker push sfsenorthamerica-build_spcs3.registry.snowflakecomputing.com/db_user0033/schema_llm/image_repo/llm-bootcamp:latest
The push refers to repository [sfsenorthamerica-build_spcs3.registry.snowflakecomputing.com/db_user0033/schema_llm/image_repo/llm-bootcamp]
Get "https:/v2/": http: no Host in request URL
```

**Comment by iamontheinet** [comment]
Please replace underscore with hyphen in your account name like so `sfsenorthamerica-build-spcs3` and try again?

**Comment by karenderer** [comment]
That worked for me, thank you.

**Comment by Luismbpr** [comment]
> Please replace underscore with hyphen in your account name like so `sfsenorthamerica-build-spcs3` and try again?

Thank you. That was the solution.

Summary:
* `cd day2`
*`docker build --platform linux/amd64 -t llm-bootcamp .`*
*`docker tag llm-bootcamp:latest sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com/db_user0033/schema_llm/image_repo/llm-bootcamp:latest`*
*`docker login sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com`* 
* Input your Username and Password
*`docker push sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com/db_user0033/schema_llm/image_repo/llm-bootcamp:latest`*

**Comment by shulik7** [comment]
> > Please replace underscore with hyphen in your account name like so `sfsenorthamerica-build-spcs3` and try again?
> 
> Thank you. That was the solution.
> 
> Summary:
> 
> * Open day2 folder on terminal.
>   _`docker build --platform linux/amd64 -t llm-bootcamp .`_
>   _`docker tag llm-bootcamp:latest sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com/db_user0033/schema_llm/image_repo/llm-bootcamp:latest`_
>   _`docker login sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com`_
> * Input your Username and Password
>   _`docker push sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com/db_user0033/schema_llm/image_repo/llm-bootcamp:latest`_

I followed this summary but got the following error when running "docker login":
Username: USER0034
Password: 
Error response from daemon: Get "https://sfsenorthamerica-build-spcs3.registry.snowflakecomputing.com/v2/": unknown: Failure: Failed to perform repository operation.

**Comment by techiex86** [comment]
I followed the directions and replaced the '_' with '-' in the hostname, but 'docker push' fails with unable to login to Snowflake.  BTW, I am able to 'docker login'.

docker push sfsenorthamerica-build-spcs4.registry.snowflakecomputing.com/db_user0037/schema_llm/image_repo/llm-bootcamp:latest

My Snowflake instance URL is https://sfsenorthamerica-build_spcs4.snowflakecomputing.com/.  

Question:  Why should 'docker push' work if the hostnames DO NOT match?
